### ISSUE TITLE
Incorrect convolution computation in a specific case on Xtensa HiFi4

### ISSUE THREAD

**Issue by lvadke** [foss-xtensa/nnlib-hifi4#14]
Hi, I described an issue with convolution computation on Xtensa HiFi4 in https://github.com/tensorflow/tflite-micro/issues/329. I think the root cause is in HiFi4 NN library as for Xtensa Fusion F1 the inputs work fine.

**Comment by cad-audio** [comment]
provided explanation for convolution fix [here](https://github.com/tensorflow/tflite-micro/issues/329)
